# .blade.yml
load_paths:
  - test/src
  - assets
  - src

logical_paths:
  - autoscoring.js
  - xcard.js
  - xcard-example.js
  - test.js
  - xcard.css

build:
  logical_paths:
    - autoscoring.js
    - xcard.js
    - xcard-example.js
    - xcard-data.js
    - xcard-data-public.js
    - xcard.css
  path: dist
  js_compressor: uglifier # Optional

require:
  - sprockets/export
